name: Deploy Pages
on:
  push:
    branches: [ "pages" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (noop example)
        run: |
          echo "Here you would run your build and copy files to $GITHUB_WORKSPACE"
